apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-carbonapps-pvc
  namespace: wso2-mdg
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  volumeName: mi-carbonapps-pv-mdg
  resources:
    requests:
      storage: 1Gi