apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-carbonapps-pv-mdg
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sc
  nfs:
    path: /var/wso2lab-nfs/caapsmdg
    server: 172.24.50.2