apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-mi-carbonapps
  namespace: wso2-dist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi