# mi-pvcs.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-carbonapps-pvc
  namespace: jerry-juma-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-conf-pvc
  namespace: jerry-juma-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-security-pvc
  namespace: jerry-juma-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi