# mi-pvcs-dist.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-carbonapps-pvc
  namespace: wso2-dist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  volumeName: mi-carbonapps-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-conf-pvc
  namespace: wso2-dist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  volumeName: mi-conf-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-security-pvc
  namespace: wso2-dist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  volumeName: mi-security-pv
  resources:
    requests:
      storage: 1Gi